CallingChilindo/Controllers/VouchersController.cs
using CallingChilindo.Business;
using CallingChilindo.Models;
using CallingChilindo.Models.Class;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CallingChilindo.Controllers
{
    public class VouchersController : Controller
    {
        // GET: Vouchers
        [Authorize]
        [HttpGet]
        public ActionResult AddVouchers()
        {
            VouchersModel vouchersModel = new VouchersModel();
            VouchersFacade vouchersFacade = new VouchersFacade();
            vouchersModel.Vouchers = new VouchersEntity();
            vouchersModel.ListVoucherTypes = vouchersFacade.GetAllVoucherType();
            vouchersModel.ListVouchers = vouchersFacade.GetAllVouchers();
            return View(vouchersModel);
        }

        [HttpPost]
        public ActionResult AddVouchers(string jsonData)
        {
            try
            {
                var voucher = Newtonsoft.Json.JsonConvert.DeserializeObject<VouchersEntity>(jsonData);
                VouchersFacade vouchersFacade = new VouchersFacade();
                if (voucher.typeOfVoucher == 1 || voucher.typeOfVoucher == 2)
                {
                    try
                    {
                        voucher.val = Convert.ToDecimal(voucher.additional);
                    }
                    catch
                    {
                        voucher.val = 0;
                    }
                }
                else
                    voucher.val = 0;

                var isSuccess = vouchersFacade.AddVoucher(voucher);

                return Json(new
                {
                    Valid = isSuccess,
                    Message = string.Empty,
                });
            }
            catch (Exception e)
            {
                return Json(new
                {
                    Valid = false,
                    Message = string.Empty,
                });
            }
        }
        [HttpPost]
        public ActionResult SetActive(string voucherId,string IsActive)
        {
            try
            {
                bool isActive = false;
                if (IsActive == "1")
                    isActive = true;
                VouchersFacade vouchersFacade = new VouchersFacade();

                if (vouchersFacade.UpdateVoucher(Convert.ToInt32(voucherId), isActive))
                {
                    return Json(new
                    {
                        Valid = true,
                        Error = string.Empty,
                    });
                }
                else
                {
                    return Json(new
                    {
                        Valid = false
                    });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Valid = false
                });

            }
        }












    }
}

CallingChilindo/Views/Vouchers/AddVouchers.cshtml
@{
    ViewBag.Title = "AddVouchers";
    Layout = "~/Views/Shared/_PostLogin.cshtml";
}
@using System.Web.Mvc.Html
@model CallingChilindo.Models.VouchersModel
@{
}
<script src="~/Content/js/jquery-ui.min.js"></script>
<script src="~/Content/asset/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<script src="~/Content/js/jquery.idletimer.js"></script>
<style>
    .modal {
       position: absolute;
       top: 200px;
       bottom: 0;
       left: 0;
       z-index: 10;
       overflow: auto;
       overflow-y: auto;
    }
</style>
<script type="text/javascript">

    function validateNumber(e) {
        var valid = true;
        var keyCode = e.charCode ? e.charCode : (window.event) ? window.event.keyCode : e.which;

        // Allow: backspace, delete, tab, escape, and enter
        if (keyCode == 46 || keyCode == 8 || keyCode == 9 ||
            // Allow: home, end, left, right
            (keyCode >= 35 && keyCode <= 39)
           ) {
            // let it happen, don't do anything
            valid = true;
        }
        else {
            // Ensure that it is a number and stop the keypress
            if ((keyCode < 48 || keyCode > 57)) {
                keyCode = 0;
                valid = false;
            }
        }

        return (valid);
    }
    var voucherId, selectedSender;
    deleteVoucher = function (id, sender) {
        voucherId = id;
        $('#deleteModal').modal('show');
    };

    confirmDelete = function () {
        $('#deleteModal').modal('hide');
        $.ajax({
            url: '@Url.Action("DeletePaymentReceipts", "Payments")',
            type: "POST",
            data: { "paymentReceiptId": voucherId },
            dataType: "json",
            success: function (result) {
                if (result.Valid) {
                    $.growl.notice({ title: "Success", message: "Payment Receipts delete successfully." });
                    location.reload();
                } else {
                    $.growl.error({ title: "Error", message: "Payment Receipts could not delete. Please check again." });
                }
            },
            error: function (xhr) {
                if (xhr.status === 401) {
                    console.log('Session Timeout');
                    location.replace('@FormsAuthentication.LoginUrl');
                    return;
                } else {
                    $.growl.error({ title: "Error", message: "Please try again." });
                }
            }
        });
        return false;
    };
    function saveVoucher() {
        var vouchercode = $("#Vouchers_voucherCode").val();
        var maxRedemptions = $("#Vouchers_maxRedemptions").val();
        var additional = $("#Vouchers_additional").val();
        var typeOfVoucher = $('[name="typeOfVoucher"]:checked').val();
        var minPurchasePrice = $("#Vouchers_minPurchasePrice").val();
        var message = '';
        if (vouchercode == '') {
            $.growl.error({ message: 'Please enter the voucher code.' }); return false;
        } else if (maxRedemptions == '') {
            $.growl.error({ message: 'Please enter the max redemptions.' }); return false;
        } else if (additional == '') {
            $.growl.error({ message: 'Please enter the additional.' }); return false;
        } else if (typeOfVoucher == undefined) {
            $.growl.error({ message: 'Please select an option to type of voucher.' }); return false;
        } else if (minPurchasePrice == '') {
            $.growl.error({ message: 'Please enter the min purchase price' }); return false;
        }
        Voucher = {
            vouchercode: vouchercode,
            maxRedemptions: maxRedemptions,
            additional: additional,
            typeOfVoucher: typeOfVoucher,
            minPurchasePrice: minPurchasePrice
        }
        $.ajax({
            url: '@Url.Action("AddVouchers", "Vouchers")',
            type: "POST",
            data: { jsonData: JSON.stringify(Voucher) },
            dataType: "json",
            success: function (result) {
                if (result.Valid) {
                    $.growl.notice({ title: "Success", message: "Voucher insert successfully." });
                    location.reload();
                } else {
                    $.growl.error({ message: 'An error occurred, Please try again.' });
                    location.reload();
                }
            },
            error: function (xhr) {
                $.growl.error({ message: 'An error occurred, Please try again.' });
            }
        });
    }
</script>
<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Confrim Delete</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure delete</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="confirmDelete();">Delete</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="section service">
    <div class="container">
        <section id="vouchersForm">
            @*<div class="row">
                <div class="col-lg-12">
                    <h4 class="classic-title"><span><b>Vouchers</b></span></h4>
                </div>
            </div>*@
            <div class="panel panel-info" id="addVoucher">
                <div class="panel-heading">
                    <h2>Add Vouchers</h2>
                </div>
                <div class="panel-body">
                    <form role="form" class="form-horizontal" id="frmpaymentreceiptdata">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-sm-2">
                                        <div data-toggle="tooltip" title="Enter the Voucher Code." class="col-sm-12">
                                            @Html.HiddenFor(model => model.Vouchers.id)
                                            @Html.LabelFor(model => model.Vouchers.voucherCode)
                                            @Html.TextBoxFor(model => model.Vouchers.voucherCode, new { @class = "form-control", @maxlength = 50 })
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div data-toggle="tooltip" title="Enter the Max Redemptions." class="col-sm-12">
                                            @Html.LabelFor(model => model.Vouchers.maxRedemptions)
                                            @Html.TextBoxFor(model => model.Vouchers.maxRedemptions, new { @class = "form-control", @maxlength = 16,  @onkeypress = "return validateNumber(event);" })
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div data-toggle="tooltip" title="Enter the Amount." class="col-sm-12">
                                            @Html.LabelFor(model => model.Vouchers.additional)
                                            @Html.TextBoxFor(model => model.Vouchers.additional, new { @class = "form-control", @maxlength = 500 })
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div data-toggle="tooltip" title="Enter the Type of Voucher." class="col-sm-12">
                                            @Html.LabelFor(model => model.Vouchers.typeOfVoucher)
                                            @foreach (var item in Model.ListVoucherTypes)
                                        {
                                            if (Model.Vouchers.voucherTypeId == item.id)
                                            {
                                        <label>@Html.RadioButton("typeOfVoucher", item.id, true)&nbsp;@item.voucherType</label><br />
                                            }
                                            else
                                            {
                                        <label>@Html.RadioButton("typeOfVoucher", item.id)&nbsp;@item.voucherType</label><br />
                                            }
                                        }
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div data-toggle="tooltip" title="Enter the Min Purchase Price." class="col-sm-12">
                                            @Html.LabelFor(model => model.Vouchers.minPurchasePrice)
                                            @Html.TextBoxFor(model => model.Vouchers.minPurchasePrice, new { @class = "form-control", @maxlength = 16, @onkeypress = "return validateNumber(event);" })
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div data-toggle="tooltip" class="col-sm-12">
                                            <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                            <button id="btnCreate" class="btn btn-large btn-success" onclick="return saveVoucher();">Create</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="panel panel-info" id="listVoucher">
                <div class="panel-heading">
                    <h2>List Vouchers</h2>
                </div>
                <div class="panel-body">
                    <div id="dvSearchResult">
                        @if (Model.ListVouchers != null)
                        {
                            Html.RenderPartial("~/Views/Vouchers/ListVoucher.cshtml", Model);
                        }
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

CallingChilindo/Views/Vouchers/ListVoucher.cshtml
@model CallingChilindo.Models.VouchersModel

<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
<style>
    .label {
        font-size: 1.0em;
    }
    
    table.dataTable tbody th, table.dataTable tbody td {
        padding: 15px;
    }

    .toggle.btn {
        zoom: 70%;
    }

    #tblVouchers thead th, #tblVouchers thead td {
        padding: 10px 18px;
        border-bottom: 1px solid #0099FF;
        color: #0099FF;
    }

    #tblVouchers tbody td {
        padding: 8px 10px;
        color: #0099FF;
    }

    #tblVouchers.row-border tbody th, #tblVouchers.row-border tbody td, #tblVouchers.display tbody th, #tblVouchers.display tbody td {
        border-top: 1px solid #C0E3F0;
        color: #0099FF;
    }

    #tblVouchers.stripe tbody tr.odd, #tblVouchers.display tbody tr.odd {
        background-color: #E0F1FD;
    }

    #tblVouchers.display tbody tr.even:hover {
        background-color: #E0F1FD;
    }

    /*#tblVouchers.display tbody tr.odd > .sorting_1, #tblVouchers.order-column.stripe tbody tr.odd > .sorting_1 {
        background-color: #C0E3F0;
    }

    #tblVouchers.order-column.hover tbody tr.even:hover > .sorting_1 {
        background-color: #C0E3F0;
    }*/

    #tblVouchers.no-footer {
        border-bottom: 1px solid #0099FF;
    }

</style>

    <table id="tblVouchers" class="display" cellspacing="0" width="100%">

        <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th align="center">Voucher Code</th>
                <th align="center">Cnt up to</th>
                <th align="center">Used in Basket</th>
                <th align="center">Amount</th>
                <th align="center">Min Purchase Price</th>
                <th align="center">Type of voucher</th>
                <th align="center">Value</th>
                <th align="center">Valid until</th>
                <th align="center">Trun off</th>
            </tr>
        </thead>

        <tbody>
            @{
                int nCount = 0;
                foreach (var item in Model.ListVouchers)
                {
                    nCount++;
                    <tr style="position:static">
                        <th>@nCount</th>
                        <th>@item.id</th>
                        <th>@item.voucherCode</th>
                        <th>@item.maxRedemptions</th> 
                        <th>@item.useInbasket</th>   
                        <th>@item.additional</th>      
                        <th>@item.minPurchasePrice</th>
                        <th>@item.voucherType</th>
                        <th>@item.val</th>                 
                        <th>@item.valid</th> 
                        <td>
                            @if ((bool)item.isActive!=null)
                            {
                                if ((bool)item.isActive)
                                {
                                    <div data-toggle="tooltip" title="This shows the current status of this voucher as active or inactive. Set the status to 'Active' if this voucher is active or 'Inactive' other wise ."><input type="checkbox" checked="checked" class="activeStatus" id="@item.id" onchange="SetActive('@item.id','0');" /></div>
                                }
                                else
                                {
                                    <div data-toggle="tooltip" title="This shows the current status of this voucher as active or inactive. Set the status to 'Active' if this voucher is active or 'Inactive' other wise .">
                                        <input type="checkbox" class="activeStatus" id="@item.id" onchange="SetActive('@item.id','1');" />
                                    </div>
                                }
                            }
                        </td>                                                                                                                                                              
                    </tr>
                }
            }
        </tbody>
    </table>
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $(".activeStatus").bootstrapToggle({
                on: 'Active',
                off: 'In-active',
                onstyle: "success",
                offstyle: "danger"
            });
        });
        $('#tblVouchers').dataTable({
            "pageLength": @Model.ListVouchers.Count(),
            "oLanguage": {
                "sEmptyTable": "No callers yet"
            }
        });

        function SetActive(obj,isactive) {
            $.ajax({
                url: "/Vouchers/SetActive",
                type: "post",
                data: { voucherId: obj, isActive: isactive },
                success: function (data) {
                    if (data.Valid) {
                        $.growl.notice({ message: 'Voucher Status updated successfully.' });
                    }
                    else {
                        $.growl.error({ message: 'An error occurred, Please try again.' });
                    }
                }
            });
        }
    </script>